Repository Vactor0911/fablab-booking-system, pull requests merged in 2025-02, with the labels that each got.

#161 Main 브랜치로부터 보안 패치 적용
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  package-lock.json
  package.json
Labels: dependencies

#168 Vactor0911
  .gitignore
  package-lock.json
  package.json
  src/components/FixedTableCell.tsx
  src/components/Header.tsx
  src/components/ReservationDialog.tsx
  src/components/SeatButton.tsx
  src/components/SeatLayout.tsx
  src/components/SeatSelecter.tsx
  src/components/TokenRefresher.tsx
  src/components/UserDialog.tsx
  src/components/tabs/CommonTabPanel.tsx
  src/components/tabs/SeatInfoTabPanel.tsx
  src/pages/BookRestrictionDetail.tsx
  src/pages/BookRestrictions.tsx
  src/pages/FindPassword.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Logs.tsx
  src/pages/MyPage.tsx
  src/pages/MyReservation.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Register.tsx
  src/pages/Reservation.tsx
  src/pages/Settings.tsx
  src/pages/Users.tsx
  src/states/index.ts
  src/utils/accessToken.ts
  src/utils/axiosInstance.ts
  src/utils/index.ts
Labels: 개선

#171 Vactor0911
  src/components/ReservationDialog.tsx
  src/components/tabs/CommonTabPanel.tsx
  src/components/tabs/SeatInfoTabPanel.tsx
  src/pages/BookRestrictionDetail.tsx
  src/pages/BookRestrictions.tsx
  src/pages/Logs.tsx
  src/pages/Reservation.tsx
  src/pages/Users.tsx
Labels: 개선

#172 Hits
  src/components/Header.tsx
  src/components/TokenRefresher.tsx
  src/components/tabs/CommonTabPanel.tsx
  src/pages/Login.tsx
Labels: 개선

#173 Vactor0911
  src/components/PasswordValidation.tsx
  src/components/UserDialog.tsx
  src/pages/About.tsx
  src/pages/FindPassword.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Register.tsx
  src/utils/index.ts
Labels: 개선

#175 권한에 따른 정보 불러오기 악시오스 형식 수정
  src/components/ReservationDialog.tsx
  src/pages/Reservation.tsx
Labels: 개선

#177 Vactor0911
  src/components/Header.tsx
  src/components/ReservationDialog.tsx
  src/components/SeatButton.tsx
  src/components/TokenRefresher.tsx
  src/pages/Reservation.tsx
  src/states/index.ts
  src/utils/axiosInstance.ts
  src/utils/index.ts
Labels: 버그, 개선

#180 Vactor0911
  src/components/Header.tsx
  src/components/ReservationDialog.tsx
Labels: 개선

#181 Dev
  src/components/Header.tsx
  src/components/ReservationDialog.tsx
Labels: 개선

#182 이슈 템플릿 업데이트
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
Labels: 문서화

#183 이슈 템플릿 삭제
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
Labels: 문서화

#184 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
Labels: 문서화

#185 오류 보고서 템플릿 수정
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/오류-보고서.md
Labels: 문서화

#186 작업 계획서 템플릿 수정
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
Labels: 문서화

#187 작업 계획서 템플릿 수정
  .github/ISSUE_TEMPLATE/2-tasks.yml
Labels: 문서화

#188 작업 계획서 템플릿 수정
  .github/ISSUE_TEMPLATE/2-tasks.yml
Labels: 문서화

#189 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
Labels: 문서화

#191 테마 적용 및 전송 로딩 상태 표시 기능 추가
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/DrawerMenu.tsx
  src/components/Header.tsx
  src/components/NoticeBanner.tsx
  src/components/ReservationDialog.tsx
  src/components/SeatButton.tsx
  src/components/SeatLayout.tsx
  src/components/SeatSelecter.tsx
  src/components/SectionHeader.tsx
  src/components/UserDialog.tsx
  src/components/tabs/CommonTabPanel.tsx
  src/components/tabs/SeatInfoTabPanel.tsx
  src/index.css
  src/pages/About.tsx
  src/pages/BookRestrictionDetail.tsx
  src/pages/BookRestrictions.tsx
  src/pages/FindPassword.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Logs.tsx
  src/pages/MyPage.tsx
  src/pages/MyReservation.tsx
  src/pages/Notice.tsx
  src/pages/NoticeDetail.tsx
  src/pages/Register.tsx
  src/pages/Reservation.tsx
  src/pages/Settings.tsx
  src/pages/Users.tsx
  src/states/index.ts
  src/utils/index.ts
  src/utils/theme.ts
Labels: 개선

#192 웹 페이지 세부 디자인 작업
  src/components/Header.tsx
  src/components/UserDialog.tsx
  src/index.css
  src/pages/MyPage.tsx
  src/pages/Notice.tsx
  src/pages/Register.tsx
  src/pages/Reservation.tsx
  src/pages/Settings.tsx
  src/utils/index.ts
Labels: 개선

#194 Vactor0911
  package-lock.json
  package.json
  src/components/QuillEditor.tsx
  src/components/WidthdrawDialog.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/NoticeDetail.tsx
Labels: 개선

#195 예약 대화상자 예약 날짜 표시 정보 변경
  src/components/ReservationDialog.tsx
Labels: 개선

#196 예약 대화상자 출력 내용 및 오류 수정
  src/components/ReservationDialog.tsx
  src/components/SeatButton.tsx
  src/components/SeatLayout.tsx
Labels: 버그, 개선

#197 타임피커 컴포넌트 구현
  src/components/TimePicker.tsx
  src/components/tabs/CommonTabPanel.tsx
Labels: 개선

#198 타임피커 다크모드 스타일 변경 및 날짜 객체 오류 수정
  src/components/TimePicker.tsx
Labels: 개선

#199 푸터 스타일 변경
  src/App.tsx
  src/assets/icons/Github.svg
  src/assets/icons/GithubWhite.svg
  src/assets/icons/Youtube.svg
  src/components/Footer.tsx
  src/utils/index.ts
Labels: 개선

#200 오류 수정
  src/components/Footer.tsx
  src/components/QuillEditor.tsx
Labels: 버그, 오류 의심

#201 프로젝트 납품 준비
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/Github.svg
  src/assets/icons/GithubWhite.svg
  src/assets/icons/Youtube.svg
  src/components/Footer.tsx
  src/components/QuillEditor.tsx
  src/components/ReservationDialog.tsx
  src/components/SeatButton.tsx
  src/components/SeatLayout.tsx
  src/components/TimePicker.tsx
  src/components/WidthdrawDialog.tsx
  src/components/tabs/CommonTabPanel.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/NoticeDetail.tsx
  src/utils/index.ts
Labels: 개선
